// <auto-generated />
using System;
using Fnyo.Learn.Jenkins.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fnyo.Learn.Jenkins.Migrations
{
    [DbContext(typeof(TmsDbContext))]
    [Migration("20211228040443_v0.0.6")]
    partial class v006
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Fnyo.Learn.Jenkins.Entity.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasColumnType("longtext")
                        .HasColumnName("author");

                    b.Property<string>("BookName")
                        .HasColumnType("longtext")
                        .HasColumnName("book_name");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("Press")
                        .HasColumnType("longtext")
                        .HasColumnName("press");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.Property<string>("Types")
                        .HasColumnType("longtext")
                        .HasColumnName("types");

                    b.HasKey("Id");

                    b.ToTable("tms_book");
                });

            modelBuilder.Entity("Fnyo.Learn.Jenkins.Entity.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("Class")
                        .HasColumnType("longtext")
                        .HasColumnName("class");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("Number")
                        .HasColumnType("longtext")
                        .HasColumnName("number");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext")
                        .HasColumnName("sex");

                    b.Property<string>("Tel")
                        .HasColumnType("longtext")
                        .HasColumnName("tel");

                    b.HasKey("Id");

                    b.ToTable("tms_student");
                });
#pragma warning restore 612, 618
        }
    }
}
