// <auto-generated />
using System;
using Fnyo.Learn.Jenkins.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fnyo.Learn.Jenkins.Migrations
{
    [DbContext(typeof(TmsDbContext))]
    partial class TmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("Fnyo.Learn.Jenkins.Entity.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasColumnType("longtext")
                        .HasColumnName("author");

                    b.Property<string>("BookName")
                        .HasColumnType("longtext")
                        .HasColumnName("book_name");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<string>("Press")
                        .HasColumnType("longtext")
                        .HasColumnName("press");

                    b.Property<double>("Price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.Property<string>("Types")
                        .HasColumnType("longtext")
                        .HasColumnName("types");

                    b.HasKey("Id");

                    b.ToTable("tms_book");
                });

            modelBuilder.Entity("Fnyo.Learn.Jenkins.Entity.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("Class")
                        .HasColumnType("longtext")
                        .HasColumnName("class");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("Number")
                        .HasColumnType("longtext")
                        .HasColumnName("number");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext")
                        .HasColumnName("sex");

                    b.Property<string>("Tel")
                        .HasColumnType("longtext")
                        .HasColumnName("tel");

                    b.HasKey("Id");

                    b.ToTable("tms_student");
                });

            modelBuilder.Entity("Fnyo.Learn.Jenkins.Entity.StudentScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Class")
                        .HasColumnType("int")
                        .HasColumnName("class");

                    b.Property<int>("ExamineType")
                        .HasColumnType("int")
                        .HasColumnName("examine_type");

                    b.Property<DateTime>("ImportTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("import_time");

                    b.Property<bool>("IsBest")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_best");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<int>("Ranking")
                        .HasColumnType("int")
                        .HasColumnName("ranking");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("score");

                    b.Property<string>("StudentName")
                        .HasColumnType("longtext")
                        .HasColumnName("student_name");

                    b.HasKey("Id");

                    b.ToTable("tms_score");
                });

            modelBuilder.Entity("Fnyo.Learn.Jenkins.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("RealName")
                        .HasColumnType("longtext")
                        .HasColumnName("real_name");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext")
                        .HasColumnName("telephone");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("tms_user");
                });
#pragma warning restore 612, 618
        }
    }
}
